version: '4.8.1'
services:
    # db:
    #     image: mysql
    #     volumes:
    #         - ./server:/docker-entrypoint-initdb.d:ro
    #     environment:
    #         MYSQL_ROOT_PASSWORD: toor
    #         MYSQL_DATABASE: rhubarb
    #         MYSQL_USER: admin
    #         MYSQL_PASSWORD: toor
    #     ports:
    #         - "3306:3306"
    server:
        build: .
        # depends_on:
        #     - db
        volumes:
            - ./rhubarb:/mnt/rhubarb:rw
            - ./nvim:/root/.config/nvim:ro
        ports:
            - 6060:3000
        # links:
        #     - "db"